# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name:  Home
    url: #_index.md
    weight: 30
  - name: Teaching and Outreach
    url: teaching-outreach
    weight: 40
  - name: People
    url: people
    weight: 50
  - name: Events
    url: events
    weight: 60
  - name: Publications
    url: publication
    weight: 70
  - name: Recorded Talks
    url: recordedtalks
    weight: 80
  - name: Openings
    url: openings
    weight: 90
  - name: Contact
    url: contact
    weight: 100
